FOSWIKI_ROOT?=~/foswiki/trunk/core
TARGET= \
  moreformfields.css \
  networkaddress.js \
  userfield.js \
  topicfield.js \
  phonenumber.js

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include
